services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  advertisement:
    build: .
    ports:
      - 3000:3000
    environment:
      - HTTP_HOST=localhost
      - HTTP_PORT=3000
      - MONGO_URL=mongodb://mongo:27017

